name: MusicTracker build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Unit test
        run: npm run test:unit
      # - name: Test
      #   run: npm run test
      #   working-directory: musictracker
      # - name: Upload build output
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: fe-build-dist
      #     path: frontend/dist
