name: Publish Cypress Repo

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@07c4d7b3def0a8ebe788a8f2c843a4e1de4f6900
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DEPLOY_OPENSSH_PRIVATE_KEY }}
        with:
          source-directory: 'musictracker'
          destination-github-username: 'xebiaquality'
          destination-repository-name: 'cypress-training-app'
          user-email: bot@xebia.com
          target-branch: main
